name: Buil Go and release

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build go binaries using the application Makefile 
      id: build_binaries
      run: |
        make build-new-version
