name: Go build and create release

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Go build and create release
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
 
    - name: Create info for the new release
      id: release_info
      run: |
        git fetch --all        
        echo $(git tag -l --sort=v:refname)
