name: Go build and release

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and release Go package
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

   # - name: Build binaries using Makefile
   #   id: build_binaries
   #   run: |
   #     go mod download
   #     make build-new-version
    
    - name: Create release info
      id: release_info
      run: |
        echo ::set-output name=new_version::$(go run cmd/releaselog/main.go version)
        echo ::set-output name=changelog::$(go run cmd/releaselog/main.go changelog)
        echo ::set-output name=title::$(go run cmd/releaselog/main.go title)
   
    - name: Create new release
      id: create_release
      uses: actions/create-release@v1
      if: ${{ steps.release_info.outputs.new_version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.release_info.outputs.new_version }}
        release_name: ${{ steps.release_info.outputs.title }}
        body: ${{ steps.release_info.outputs.changelog }}
        draft: true
      
